UPDATE employees SET siprahub_email = 'sachin@siprahub.com' WHERE LOWER(rms_name) = LOWER('Sachin Mishra');
UPDATE employees SET siprahub_email = 'harishashok@siprahub.com' WHERE LOWER(rms_name) = LOWER('HARISH ASHOK GAWAI');
UPDATE employees SET siprahub_email = 'yogesh@siprahub.com', aws_email = 'yogesh.vanakapadne@dcli.com' WHERE LOWER(rms_name) = LOWER('Yogesh Vana Kapadne');
UPDATE employees SET siprahub_email = 'mohinuddin@siprahub.com', aws_email = 'sk.mohinuddin@dcli.com' WHERE LOWER(rms_name) = LOWER('Sk Mohinuddin');
UPDATE employees SET siprahub_email = 'madan@siprahub.com', aws_email = 'madan.kumar@dcli.com' WHERE LOWER(rms_name) = LOWER('Madan Kumar');
UPDATE employees SET siprahub_email = 'vishnu@siprahub.com', aws_email = 'vishnu.vardhan@dcli.com' WHERE LOWER(rms_name) = LOWER('Vishnu Vardhan');
UPDATE employees SET siprahub_email = 'naveens@siprahub.com', aws_email = 'naveen.kumar@dcli.com' WHERE LOWER(rms_name) = LOWER('Naveen Kumar S');
UPDATE employees SET siprahub_email = 'naresh@siprahub.com', aws_email = 'naresh.chirra@dcli.com' WHERE LOWER(rms_name) = LOWER('Naresh Chirra');
UPDATE employees SET siprahub_email = 'naveen@siprahub.com' WHERE LOWER(rms_name) = LOWER('Naveen Prakash');
UPDATE employees SET siprahub_email = 'ramji.bora@siprahub.com', aws_email = 'ramji.bora@dcli.com' WHERE LOWER(rms_name) = LOWER('Ramji Bora');
UPDATE employees SET siprahub_email = 'charles@siprahub.com', aws_email = 'arockiaraj.charles@dcli.com' WHERE LOWER(rms_name) = LOWER('Arockiaraj Charles');
UPDATE employees SET siprahub_email = 'aamir@siprahub.com', aws_email = 'aamir.bashir@dcli.com' WHERE LOWER(rms_name) = LOWER('Aamir Bashir');
UPDATE employees SET siprahub_email = 'jinesh@siprahub.com' WHERE LOWER(rms_name) = LOWER('Jinesh Modi');
UPDATE employees SET siprahub_email = 'kondala@siprahub.com' WHERE LOWER(rms_name) = LOWER('kondala.reddy.y');
UPDATE employees SET siprahub_email = 'rajesh@siprahub.com' WHERE LOWER(rms_name) = LOWER('Rajesh K');
UPDATE employees SET siprahub_email = 'manohar@siprahub.com' WHERE LOWER(rms_name) = LOWER('Manohar G');
UPDATE employees SET siprahub_email = 'nagarajup@siprahub.com' WHERE LOWER(rms_name) = LOWER('NAGARAJU PENUGONDA');
UPDATE employees SET siprahub_email = 'rahuludugula@siprahub.com', aws_email = 'rahul.udugula@dcli.com' WHERE LOWER(rms_name) = LOWER('RAHUL UDUGULA');
UPDATE employees SET siprahub_email = 'baburao@siprahub.com', aws_email = 'marla.baburao@dcli.com' WHERE LOWER(rms_name) = LOWER('Marla Baburao');
UPDATE employees SET siprahub_email = 'laxman@siprahub.com', aws_email = 'laxman.lingampally@dcli.com' WHERE LOWER(rms_name) = LOWER('Laxman Lingampally');
UPDATE employees SET siprahub_email = 'vinay@siprahub.com' WHERE LOWER(rms_name) = LOWER('Vinay Kumar KN');
UPDATE employees SET siprahub_email = 'lalithanjali@siprahub.com' WHERE LOWER(rms_name) = LOWER('Lalithanjali Bethu');
UPDATE employees SET siprahub_email = 'tawseef@siprahub.com' WHERE LOWER(rms_name) = LOWER('Tawseef Ahmed Bhat');
UPDATE employees SET siprahub_email = 'jitendra.vyas@siprahub.com', aws_email = 'jitendra.vyas@dcli.com' WHERE LOWER(rms_name) = LOWER('JITENDRA VYAS');
UPDATE employees SET siprahub_email = 'bharath@siprahub.com' WHERE LOWER(rms_name) = LOWER('Bharath Kumar Reddy Bireddy');
UPDATE employees SET siprahub_email = 'maheswaraiah@siprahub.com' WHERE LOWER(rms_name) = LOWER('Maheswaraiah Gali');
UPDATE employees SET siprahub_email = 'divya@siprahub.com' WHERE LOWER(rms_name) = LOWER('Divya Bitla');
UPDATE employees SET siprahub_email = 'satyam.pamar@siprahub.com', aws_email = 'satyam.parmar@dcli.com' WHERE LOWER(rms_name) = LOWER('SATYAM SINGH PARMAR');
UPDATE employees SET siprahub_email = 'navneet@siprahub.com', aws_email = 'navneet.tiwari@dcli.com' WHERE LOWER(rms_name) = LOWER('Navneet Tiwari');
UPDATE employees SET siprahub_email = 'amit@siprahub.com' WHERE LOWER(rms_name) = LOWER('Amit Singh');
UPDATE employees SET siprahub_email = 'gopalakrishnan@siprahub.com', aws_email = 'gopalakrishnan.rangaswamy@dcli.com' WHERE LOWER(rms_name) = LOWER('GOPALAKRISHNAN RANGASWAMY');
UPDATE employees SET siprahub_email = 'eswar@siprahub.com', aws_email = 'eswar.kumar@dcli.com' WHERE LOWER(rms_name) = LOWER('Eswar Kumar');
UPDATE employees SET siprahub_email = 'jahangir@siprahub.com' WHERE LOWER(rms_name) = LOWER('Alam Jahangir');
UPDATE employees SET siprahub_email = 'abhishekthakur@siprahub.com' WHERE LOWER(rms_name) = LOWER('ABHISHEK THAKUR');
UPDATE employees SET siprahub_email = 'vishal@siprahub.com', aws_email = 'vishal.gulati@dcli.com' WHERE LOWER(rms_name) = LOWER('Vishal Gulati');
UPDATE employees SET siprahub_email = 'nitish@siprahub.com', aws_email = 'nitish.gulati@dcli.com' WHERE LOWER(rms_name) = LOWER('Nitish Gulati');
UPDATE employees SET siprahub_email = 'rafee@siprahub.com', aws_email = 'rafee.qureshi@dcli.com' WHERE LOWER(rms_name) = LOWER('Rafee Qureshi');
UPDATE employees SET siprahub_email = 'janardhana@siprahub.com', aws_email = 'janardhanarao.batna@dcli.com' WHERE LOWER(rms_name) = LOWER('Janardhanaraeo Batna');
UPDATE employees SET siprahub_email = 'srikanth@siprahub.com' WHERE LOWER(rms_name) = LOWER('Srikanth Reddy Angeri');
UPDATE employees SET siprahub_email = 'nagaraju@siprahub.com', aws_email = 'nagaraju.alluru@dcli.com' WHERE LOWER(rms_name) = LOWER('Nagaraju Alluru');
UPDATE employees SET siprahub_email = 'purna@siprahub.com', aws_email = 'purna.mandalaneni@dcli.com' WHERE LOWER(rms_name) = LOWER('Purna Mandalaneni');
UPDATE employees SET siprahub_email = 'vinod@siprahub.com', aws_email = 'vinod.kakumani@dcli.com' WHERE LOWER(rms_name) = LOWER('Vinod Kakumani');
UPDATE employees SET siprahub_email = 'sirivella@siprahub.com' WHERE LOWER(rms_name) = LOWER('Sirivella Mallikarjuna');
UPDATE employees SET siprahub_email = 'sriramarajub@siprahub.com' WHERE LOWER(rms_name) = LOWER('SRIRAMARAJU BUDDHARAJU');
UPDATE employees SET siprahub_email = 'siva@siprahub.com', aws_email = 'siva.kumar@dcli.com' WHERE LOWER(rms_name) = LOWER('Siva Kumar');
UPDATE employees SET siprahub_email = 'ravindra@siprahub.com' WHERE LOWER(rms_name) = LOWER('Ravindra Kumar Vemuri');
UPDATE employees SET siprahub_email = 'charank@siprahub.com' WHERE LOWER(rms_name) = LOWER('CHARAN KOTHAMASU');
UPDATE employees SET siprahub_email = 'sravanijonnalagadda@siprahub.com' WHERE LOWER(rms_name) = LOWER('SRAVANI JONNALAGADDA');
UPDATE employees SET siprahub_email = 'sameer@siprahub.com' WHERE LOWER(rms_name) = LOWER('Sameer Kumar P');
UPDATE employees SET siprahub_email = 'latharamachandra@siprahub.com', aws_email = 'latha.ramachandra@dcli.com' WHERE LOWER(rms_name) = LOWER('LATHA RAMACHANDRA');
UPDATE employees SET siprahub_email = 'siddhartha@siprahub.com' WHERE LOWER(rms_name) = LOWER('Siddhartha Bhowmick');
UPDATE employees SET siprahub_email = 'arvind@siprahub.com' WHERE LOWER(rms_name) = LOWER('Arvind Kishore');
UPDATE employees SET siprahub_email = 'praneeth@siprahub.com', aws_email = 'praneeth.nageshwar.p@dcli.com' WHERE LOWER(rms_name) = LOWER('Praneeth Nageshwar.P');
UPDATE employees SET siprahub_email = 'deepak@siprahub.com' WHERE LOWER(rms_name) = LOWER('Deepak Raj');
UPDATE employees SET siprahub_email = 'sneha flora' WHERE LOWER(rms_name) = LOWER('SNEHA FLORA S');
UPDATE employees SET siprahub_email = 'shravan@siprahub.com' WHERE LOWER(rms_name) = LOWER('Shravan Kosoju');
UPDATE employees SET siprahub_email = 'vishalkumar@siprahub.com' WHERE LOWER(rms_name) = LOWER('Vishal Kumar');
UPDATE employees SET siprahub_email = 'srinivas@siprahub.com', aws_email = 'srinivas.vutukuri@dcli.com' WHERE LOWER(rms_name) = LOWER('Srinivas Vutukuri');
UPDATE employees SET siprahub_email = 'rahul@siprahub.com' WHERE LOWER(rms_name) = LOWER('Rahul Kumar Vommi');
UPDATE employees SET siprahub_email = 'jay@siprahub.com', aws_email = 'jay.maniar@dcli.com' WHERE LOWER(rms_name) = LOWER('Jay Maniar');
UPDATE employees SET siprahub_email = 'bala@siprahub.com' WHERE LOWER(rms_name) = LOWER('Bala Phani Kumar Kakuleti');
UPDATE employees SET siprahub_email = 'pavank@siprahub.com', aws_email = 'pavan.kondagattu@dcli.com' WHERE LOWER(rms_name) = LOWER('Pavan Kondagattu');
UPDATE employees SET siprahub_email = 'mallikarjuna@siprahub.com' WHERE LOWER(rms_name) = LOWER('Mallikarjuna Rao Ponnaganti');
UPDATE employees SET siprahub_email = 'ashokp@siprahub.com' WHERE LOWER(rms_name) = LOWER('Ashok Pallapu');
UPDATE employees SET siprahub_email = 'ventatesh@siprahub.com' WHERE LOWER(rms_name) = LOWER('Venkatesh Vallabdas');
UPDATE employees SET siprahub_email = 'kalyanp@siprahub.com', aws_email = 'kalyan.parsi@dcli.com' WHERE LOWER(rms_name) = LOWER('KALYAN PARSI');
UPDATE employees SET siprahub_email = 'jagadish@siprahub.com' WHERE LOWER(rms_name) = LOWER('Jagadish Garina');
UPDATE employees SET siprahub_email = 'mitra@siprahub.com' WHERE LOWER(rms_name) = LOWER('Mitra Akshar');
UPDATE employees SET siprahub_email = 'paresh@siprahub.com' WHERE LOWER(rms_name) = LOWER('paresh');
UPDATE employees SET siprahub_email = 'deepakk@siprahub.com' WHERE LOWER(rms_name) = LOWER('Deepak Kumar');
UPDATE employees SET siprahub_email = 'prasadr@siprahub.com' WHERE LOWER(rms_name) = LOWER('PRASAD REDDY GKV');
UPDATE employees SET siprahub_email = 'naveenr@siprahub.com' WHERE LOWER(rms_name) = LOWER('NaveenKumar R');
UPDATE employees SET siprahub_email = 'sheiks@siprahub.com' WHERE LOWER(rms_name) = LOWER('SHEIK SALIM');
UPDATE employees SET siprahub_email = 'thrinadhkumar@siprahub.com' WHERE LOWER(rms_name) = LOWER('THRINADH KUMAR');
UPDATE employees SET siprahub_email = 'madhug@siprahub.com' WHERE LOWER(rms_name) = LOWER('MADHU GANDLURI');
UPDATE employees SET siprahub_email = 'brajs@siprahub.com', aws_email = 'braj.sharma@dcli.com' WHERE LOWER(rms_name) = LOWER('BRAJ SHARMA');
UPDATE employees SET siprahub_email = 'shruthis@siprahub.com' WHERE LOWER(rms_name) = LOWER('SHRUTHI SHANTHAPPA');
UPDATE employees SET siprahub_email = 'narmathamariappan@siprahub.com' WHERE LOWER(rms_name) = LOWER('NARMATHA MARIAPPAN');
UPDATE employees SET siprahub_email = 'samratsv@siprahub.com', aws_email = 'srivelu.samrat@dcli.com' WHERE LOWER(rms_name) = LOWER('SRIVELU VINAYAKA SAMRAT');
UPDATE employees SET siprahub_email = 'yukeshkumar@siprahub.com' WHERE LOWER(rms_name) = LOWER('YUKESH KUMAR');
UPDATE employees SET siprahub_email = 'pawankotturi@siprahub.com' WHERE LOWER(rms_name) = LOWER('PAWAN KOTTURI');
UPDATE employees SET siprahub_email = 'sandeep.sharma@siprahub.com', aws_email = 'sandeep.sharma@dcli.com' WHERE LOWER(rms_name) = LOWER('SANDEEP SHARMA');
UPDATE employees SET siprahub_email = 'uvaismohammed@siprahub.com' WHERE LOWER(rms_name) = LOWER('UVAIS MOHAMMED');
UPDATE employees SET siprahub_email = 'pavan@siprahub.com', aws_email = 'pavan.talluri@dcli.com' WHERE LOWER(rms_name) = LOWER('Pavan Talluri');
UPDATE employees SET siprahub_email = 'shamini@siprahub.com', aws_email = 'shamini.bommi@dcli.com' WHERE LOWER(rms_name) = LOWER('Shamini Mary Bommi');
UPDATE employees SET siprahub_email = 'rajesha@siprahub.com', aws_email = 'rajesh.arcot@dcli.com' WHERE LOWER(rms_name) = LOWER('Rajesh Arcot');
UPDATE employees SET siprahub_email = 'venkata@siprahub.com', aws_email = 'venkata.gummaraju@dcli.com' WHERE LOWER(rms_name) = LOWER('Venkata Karthik Gummaraju');
UPDATE employees SET siprahub_email = 'karunamoorthis@spirahub.com', aws_email = 'karunamoorthi.sakthivel@dcli.com' WHERE LOWER(rms_name) = LOWER('Karunamoorthi Sakthivel');
UPDATE employees SET siprahub_email = 'swathiv@siprahub.com', aws_email = 'swathi.velicheti@dcli.com' WHERE LOWER(rms_name) = LOWER('Swathi Velicheti');
UPDATE employees SET siprahub_email = 'abhishek@siprahub.com' WHERE LOWER(rms_name) = LOWER('Abhishek Singh');
UPDATE employees SET siprahub_email = 'tufail@siprahub.com', aws_email = 'tufail.mehraj@dcli.com' WHERE LOWER(rms_name) = LOWER('Tufail Mehraj');
UPDATE employees SET siprahub_email = 'dileeps@siprahub.com' WHERE LOWER(rms_name) = LOWER('Dileep Singh');
UPDATE employees SET siprahub_email = 'yaseenmajeed@siprahub.com', aws_email = 'yaseen.majeed@dcli.com' WHERE LOWER(rms_name) = LOWER('YASEEN MAJEED');
UPDATE employees SET siprahub_email = 'nareshr@siprahub.com' WHERE LOWER(rms_name) = LOWER('NARESH REDDIPALLI');
UPDATE employees SET siprahub_email = 'anoop.mishra@siprahub.com', aws_email = 'anoop.mishra@dcli.com' WHERE LOWER(rms_name) = LOWER('ANOOP MISHRA');
UPDATE employees SET siprahub_email = 'rajeshsai@siprahub.com' WHERE LOWER(rms_name) = LOWER('Rajesh Sai Krishna V');
UPDATE employees SET siprahub_email = 'gurusai@siprahub.com' WHERE LOWER(rms_name) = LOWER('GURU SAI');
UPDATE employees SET siprahub_email = 'naveen.duraisamy@siprahub.com', aws_email = 'naveen.duraisamy@dcli.com' WHERE LOWER(rms_name) = LOWER('NAVEEN KUMAR DURAISAMY');
UPDATE employees SET siprahub_email = 'desai@siprahub.com', aws_email = 'desai.chandramouli@dcli.com' WHERE LOWER(rms_name) = LOWER('Desai Shivakumar Chandramouli');
UPDATE employees SET siprahub_email = 'prabhakar@siprahub.com' WHERE LOWER(rms_name) = LOWER('Prabhakar K');
UPDATE employees SET siprahub_email = 'sivas@siprahub.com', aws_email = 'siva.shankar@dcli.com' WHERE LOWER(rms_name) = LOWER('Siva Shankar');
UPDATE employees SET siprahub_email = 'sivap@siprahub.com', aws_email = 'siva.t@dcli.com' WHERE LOWER(rms_name) = LOWER('Siva Prasad T');
UPDATE employees SET siprahub_email = 'navdeepv@siprahub.com', aws_email = 'navdeep.vanitha@dcli.com' WHERE LOWER(rms_name) = LOWER('NAVDEEP Vanitha');
UPDATE employees SET siprahub_email = 'pavanys@siprahub.com' WHERE LOWER(rms_name) = LOWER('Pavan Kumar Yeldur Sheshadri');
UPDATE employees SET siprahub_email = 'sandeepkoppula@siprahub.com', aws_email = 'sandeep.koppula@dcli.com' WHERE LOWER(rms_name) = LOWER('SANDEEP KOPPULA');
UPDATE employees SET siprahub_email = 'manasa@siprahub.com', aws_email = 'manasa.somashekar@dcli.com' WHERE LOWER(rms_name) = LOWER('Manasa Somashekar');
UPDATE employees SET siprahub_email = 'adi@siprahub.com', aws_email = 'adi.narayana@dcli.com' WHERE LOWER(rms_name) = LOWER('Adi Narayana');
UPDATE employees SET siprahub_email = 'baiju@siprahub.com', aws_email = 'baiju.k@dcli.com' WHERE LOWER(rms_name) = LOWER('Baiju B Menon C K');
UPDATE employees SET siprahub_email = 'pmanohar@siprahub.com' WHERE LOWER(rms_name) = LOWER('PHIRANGI MANOHAR SAKARE');
UPDATE employees SET siprahub_email = 'bandirao@siprahub.com' WHERE LOWER(rms_name) = LOWER('BANDI MADHAVA RAO');
UPDATE employees SET siprahub_email = 'rahulkumar@siprahub.com', aws_email = 'rahul.nagarajavari@dcli.com' WHERE LOWER(rms_name) = LOWER('Rahul Kumar Nagarajavari');
UPDATE employees SET siprahub_email = 'dillibabu@siprahub.com' WHERE LOWER(rms_name) = LOWER('DILLI BABU');
UPDATE employees SET siprahub_email = 'praveen@siprahub.com' WHERE LOWER(rms_name) = LOWER('Praveen Chowdam');
UPDATE employees SET siprahub_email = 'kirank@siprahub.com', aws_email = 'kiran.kalasapadu@dcli.com' WHERE LOWER(rms_name) = LOWER('Kiran Kumar Kalasapadu');
UPDATE employees SET siprahub_email = 'viswanath@siprahub.com' WHERE LOWER(rms_name) = LOWER('VISWANATH DEEPAK G');
UPDATE employees SET siprahub_email = 'ramv@siprahub.com' WHERE LOWER(rms_name) = LOWER('VenkatRam.M');
UPDATE employees SET siprahub_email = 'nisheethbhardwaj@siprahub.com', aws_email = 'nisheeth.bhardwaj@dcli.com' WHERE LOWER(rms_name) = LOWER('NISHEETH BHARDWAJ');
UPDATE employees SET siprahub_email = 'saisudheer@siprahub.com' WHERE LOWER(rms_name) = LOWER('Kothamasu Hanuma Sai Sudheer');
UPDATE employees SET siprahub_email = 'raghunandang@siprahub.com', aws_email = 'raghunandan.gurumurthy@dcli.com' WHERE LOWER(rms_name) = LOWER('Raghunandan Gurumurthy');
UPDATE employees SET siprahub_email = 'rajashreek@siprahub.com' WHERE LOWER(rms_name) = LOWER('RAJASREE KOTHAGATTU');
UPDATE employees SET siprahub_email = 'jaicind@siprahub.com', aws_email = 'jaicind.bhavan@dcli.com' WHERE LOWER(rms_name) = LOWER('Jaicind Santhi Bhavan');
UPDATE employees SET siprahub_email = 'chennakrishna@siprahub.com' WHERE LOWER(rms_name) = LOWER('Chennakrishna Reddy');
UPDATE employees SET siprahub_email = 'shabharishv@siprahub.com', aws_email = 'shabharish.pasupula@dcli.com' WHERE LOWER(rms_name) = LOWER('Shabharish Venkata Pasupula');
UPDATE employees SET siprahub_email = 'raja@siprahub.com', aws_email = 'raja.oruganti@dcli.com' WHERE LOWER(rms_name) = LOWER('Raja Oruganti');
UPDATE employees SET siprahub_email = 'chakravarthig@siprahub.com' WHERE LOWER(rms_name) = LOWER('CHAKRAVARTHI GONNABAKTULA');
UPDATE employees SET siprahub_email = 'pradeepk@siprahub.com' WHERE LOWER(rms_name) = LOWER('PRADEEP KONDALA');
UPDATE employees SET siprahub_email = 'manoj@siprahub.com', aws_email = 'manoj.n@dcli.com' WHERE LOWER(rms_name) = LOWER('Manoj P V N');
UPDATE employees SET siprahub_email = 'lavanya@siprahub.com', aws_email = 'lavanya.samudrala@dcli.com' WHERE LOWER(rms_name) = LOWER('Lavanya Samudrala');
UPDATE employees SET siprahub_email = 'komalshrivastava@siprahub.com' WHERE LOWER(rms_name) = LOWER('KOMAL SHRIVASTAVA');
UPDATE employees SET siprahub_email = 'shivag@siprahub.com', aws_email = 'shiva.goyal@dcli.com' WHERE LOWER(rms_name) = LOWER('Shiva Goyal');
UPDATE employees SET siprahub_email = 'shivani@siprahub.com' WHERE LOWER(rms_name) = LOWER('Shivani Mittal');
UPDATE employees SET siprahub_email = 'prabhakardhere@siprahub.com' WHERE LOWER(rms_name) = LOWER('PRABHAKAR DHERE');
UPDATE employees SET siprahub_email = 'rajasekarc@siprahub.com' WHERE LOWER(rms_name) = LOWER('RAJASEKAR CHANDRABABU');
UPDATE employees SET siprahub_email = 'kamalkishore@siprahub.com', aws_email = 'kamal.kishore@dcli.com' WHERE LOWER(rms_name) = LOWER('KAMAL KISHORE');
UPDATE employees SET siprahub_email = 'pallavic@siprahub.com' WHERE LOWER(rms_name) = LOWER('PALLAVI CHINTAPALLI');
UPDATE employees SET siprahub_email = 'rajeshkondepu@siprahub.com' WHERE LOWER(rms_name) = LOWER('RAJESH KONDEPU');
UPDATE employees SET siprahub_email = 'smitha@siprahub.com', aws_email = 'smitha.krishnan@dcli.com' WHERE LOWER(rms_name) = LOWER('SMITHA KRISHNAN');
UPDATE employees SET siprahub_email = 'samanvitha@siprahub.com', aws_email = 'samanvitha.sethuraman@dcli.com' WHERE LOWER(rms_name) = LOWER('Samanvitha Kelamangalam Sethuraman');
UPDATE employees SET siprahub_email = 'anushad@siprahub.com', aws_email = 'anusha.deja@dcli.com' WHERE LOWER(rms_name) = LOWER('Anusha Deja');
UPDATE employees SET siprahub_email = 'gohithkumar@siprahub.com' WHERE LOWER(rms_name) = LOWER('GOHITH KUMAR BATTEPATI');
UPDATE employees SET siprahub_email = 'atuldandin@siprahub.com' WHERE LOWER(rms_name) = LOWER('ATUL DANDIN');
UPDATE employees SET siprahub_email = 'sarath.s@siprahub.com' WHERE LOWER(rms_name) = LOWER('SARATH SIVAPRAKASH');
UPDATE employees SET siprahub_email = 'ramatammu@siprahub.com', aws_email = 'rama.tammu@dcli.com' WHERE LOWER(rms_name) = LOWER('RAMA Tammu');
UPDATE employees SET siprahub_email = 'soumyab@siprahub.com' WHERE LOWER(rms_name) = LOWER('Soumya Balasubramanyam');
UPDATE employees SET siprahub_email = 'deepaktogloor@siprahub.com' WHERE LOWER(rms_name) = LOWER('DEEPAK TOGLOOR');
UPDATE employees SET siprahub_email = 'rahulkhurana@siprahub.com' WHERE LOWER(rms_name) = LOWER('Rahul Khurana');
UPDATE employees SET siprahub_email = 'inthiyazsayed@siprahub.com', aws_email = 'inthiyaz.syed@dcli.com' WHERE LOWER(rms_name) = LOWER('Inthiyaz Syed');
UPDATE employees SET siprahub_email = 'priyankaghosh@siprahub.com', aws_email = 'priyanka.ghosh@dcli.com' WHERE LOWER(rms_name) = LOWER('PRIYANKA GHOSH');
UPDATE employees SET siprahub_email = 'dinakarreddy@siprahub.com', aws_email = 'dinakar.reddy@dcli.com' WHERE LOWER(rms_name) = LOWER('Dinakar Reddy');
UPDATE employees SET siprahub_email = 'lakshminarayana@siprahub.com', aws_email = 'lakshmi.narayana@dcli.com' WHERE LOWER(rms_name) = LOWER('LAKSHMI NARAYANA');
UPDATE employees SET siprahub_email = 'vijaikumar@siprahub.com', aws_email = 'vijaikumar.manoharan@dcli.com' WHERE LOWER(rms_name) = LOWER('VIJAIKUMAR MANOHARAN');
UPDATE employees SET siprahub_email = 'anudeepchillamcherla@siprahub.com', aws_email = 'anudeep.chillamcherla@dcli.com' WHERE LOWER(rms_name) = LOWER('Anudeep Chillamcherla');
UPDATE employees SET siprahub_email = 'deblinabarman@siprahub.com' WHERE LOWER(rms_name) = LOWER('DEBLINA BARMAN');
UPDATE employees SET siprahub_email = 'pujap@siprahub.com', aws_email = 'puja.patil@dcli.com' WHERE LOWER(rms_name) = LOWER('PUJA PATIL');
UPDATE employees SET siprahub_email = 'dineshkumarg@siprahub.com', aws_email = 'dineshkumar.govindarajan@dcli.com' WHERE LOWER(rms_name) = LOWER('Dineshkumar Govindarajan');
UPDATE employees SET siprahub_email = 'rajeeshu@siprahub.com', aws_email = 'rajeesh.upendran@dcli.com' WHERE LOWER(rms_name) = LOWER('Rajeesh Upendran');
UPDATE employees SET siprahub_email = 'ramzankhan@siprahub.com' WHERE LOWER(rms_name) = LOWER('RAMZAN KHAN');
UPDATE employees SET siprahub_email = 'shilendra.yadav@siprahub.com' WHERE LOWER(rms_name) = LOWER('SHILENDRA YADAV');
UPDATE employees SET siprahub_email = 'kishorea@siprahub.com', aws_email = 'kishore.ashwath@dcli.com' WHERE LOWER(rms_name) = LOWER('KISHORE ASHWATH');
UPDATE employees SET siprahub_email = 'kaushikg@siprahub.com' WHERE LOWER(rms_name) = LOWER('Kaushik Gummaraju');
UPDATE employees SET siprahub_email = 'lakshmi@siprahub.com', aws_email = 'lakshmi.sighkolli@dcli.com' WHERE LOWER(rms_name) = LOWER('Lakshmi Sighkolli');
UPDATE employees SET siprahub_email = 'adwalamadhurima@siprahub.com', aws_email = 'adwala.madhurima@dcli.com' WHERE LOWER(rms_name) = LOWER('Adwala Madhurima');
UPDATE employees SET siprahub_email = 'krishnaprasad@siprahub.com', aws_email = 'krishna.kota@dcli.com' WHERE LOWER(rms_name) = LOWER('Krishna Prasad Kota');
UPDATE employees SET siprahub_email = 'saicharan@siprahub.com' WHERE LOWER(rms_name) = LOWER('Sai Charan Dhadithotoporeddy');
UPDATE employees SET siprahub_email = 'karthikbm@siprahub.com', aws_email = 'karthik.manjunatha@dcli.com' WHERE LOWER(rms_name) = LOWER('Karthik Biradahalli Manjunatha');
UPDATE employees SET siprahub_email = 'harichandana@siprahub.com', aws_email = 'hari.duvvada@dcli.com' WHERE LOWER(rms_name) = LOWER('Hari Chandana Duvvada');
UPDATE employees SET siprahub_email = 'sasikanth@siprahub.com' WHERE LOWER(rms_name) = LOWER('Sasi Kanth N');
UPDATE employees SET siprahub_email = 'rizwanashaik@siprahub.com' WHERE LOWER(rms_name) = LOWER('RIZWANA SHAIK');
UPDATE employees SET siprahub_email = 'srinivascherukuru@siprahub.com' WHERE LOWER(rms_name) = LOWER('SRINIVAS CHERUKURU');
UPDATE employees SET siprahub_email = 'kumaresan@siprahub.com' WHERE LOWER(rms_name) = LOWER('KUMARESAN JAGADEESHAN');
UPDATE employees SET siprahub_email = 'ramcharan@siprahub.com' WHERE LOWER(rms_name) = LOWER('RAM CHARAN');
UPDATE employees SET siprahub_email = 'vipinchand@siprahub.com' WHERE LOWER(rms_name) = LOWER('VIPIN CHAND');
UPDATE employees SET siprahub_email = 'chandramohan@siprahub.com' WHERE LOWER(rms_name) = LOWER('Chandra Mohan');
UPDATE employees SET siprahub_email = 'bharatha@siprahub.com' WHERE LOWER(rms_name) = LOWER('Bharath Alla');
UPDATE employees SET siprahub_email = 'ritik@siprahub.com' WHERE LOWER(rms_name) = LOWER('Ritik Verma');
UPDATE employees SET siprahub_email = 'syed@siprahub.com', aws_email = 'syed.anees@dcli.com' WHERE LOWER(rms_name) = LOWER('SYED YASIR ANEES');
UPDATE employees SET siprahub_email = 'raju@siprahub.com', aws_email = 'raju.chiklinge@dcli.com' WHERE LOWER(rms_name) = LOWER('Raju Chiklinge');
UPDATE employees SET siprahub_email = 'divyasree@siprahub.com' WHERE LOWER(rms_name) = LOWER('Divya Sree Tangutoori');
UPDATE employees SET siprahub_email = 'ragupathyselvaraj@siprahub.com' WHERE LOWER(rms_name) = LOWER('RAGUPATHY SELVARAJ');
UPDATE employees SET siprahub_email = 'vijayapakalapati@siprahub.com' WHERE LOWER(rms_name) = LOWER('Vijaya Rama Raju Pakalapati');
UPDATE employees SET siprahub_email = 'nagaswaroopa@siprahub.com', aws_email = 'naga.rani@dcli.com' WHERE LOWER(rms_name) = LOWER('NAGA SWAROOPA RANI');
UPDATE employees SET siprahub_email = 'durgasrinivas@siprahub.com', aws_email = 'durga.wuyyuru@dcli.com' WHERE LOWER(rms_name) = LOWER('DURGA SRINIVAS WUYYURU');
UPDATE employees SET siprahub_email = 'rohinipayyavula@siprahub.com', aws_email = 'rohini.shetty@dcli.com' WHERE LOWER(rms_name) = LOWER('ROHINI PAYYAVULA SUBRAMANYA SHETTY');
UPDATE employees SET siprahub_email = 'kishorekumar@siprahub.com' WHERE LOWER(rms_name) = LOWER('KISHORE KUMAR');
UPDATE employees SET siprahub_email = 'navaneethakrishna@siprahub.com', aws_email = 'navaneethakrishnan.natarajan@dcli.com' WHERE LOWER(rms_name) = LOWER('NAVANEETHAKRISHNAN NATARAJAN');
UPDATE employees SET siprahub_email = 'muralikrishna@siprahub.com' WHERE LOWER(rms_name) = LOWER('MURALI KRISHNA GAJENDRA');
UPDATE employees SET siprahub_email = 'kannank@siprahub.com' WHERE LOWER(rms_name) = LOWER('KANNAN KARUPPUCHETTY');
UPDATE employees SET siprahub_email = 'ravikumar@siprahub.com' WHERE LOWER(rms_name) = LOWER('Ravi Kumar Kurumidde');
UPDATE employees SET siprahub_email = 'rahuladupa@siprahub.com' WHERE LOWER(rms_name) = LOWER('Rahul Adupa');
UPDATE employees SET siprahub_email = 'prakash.gunthe@siprahub.com', aws_email = 'prakash.gunthe@dcli.com' WHERE LOWER(rms_name) = LOWER('Prakash Gunthe');
UPDATE employees SET siprahub_email = 'lohithav@siprahub.com', aws_email = 'lohitha.nagara@dcli.com' WHERE LOWER(rms_name) = LOWER('Lohitha Vivekanda Nagara');
UPDATE employees SET siprahub_email = 'saikarthik@siprahub.com', aws_email = 'sai.janyavula@dcli.com' WHERE LOWER(rms_name) = LOWER('SAI KARTHIK JANYAVULA');
UPDATE employees SET siprahub_email = 'chandrasekharreddy@siprahub.com' WHERE LOWER(rms_name) = LOWER('NAGELLA CHANDRASEKHAR REDDY');
UPDATE employees SET siprahub_email = 'sriharitheja@siprahub.com' WHERE LOWER(rms_name) = LOWER('YAJAMANYA SRIHARI THEJA');
UPDATE employees SET siprahub_email = 'athulkumar@siprahub.com' WHERE LOWER(rms_name) = LOWER('ATHUL KUMAR');
UPDATE employees SET siprahub_email = 'amirashraf@siprahub.com', aws_email = 'amir.khan@dcli.com' WHERE LOWER(rms_name) = LOWER('Amir Ashraf Khan');
UPDATE employees SET siprahub_email = 'dithendrakaranam@siprahub.com' WHERE LOWER(rms_name) = LOWER('Dithendra Karanam');
UPDATE employees SET siprahub_email = 'harikumar@siprahub.com' WHERE LOWER(rms_name) = LOWER('Hari Vinoth Kumar');
UPDATE employees SET siprahub_email = 'karthikm@siprahub.com' WHERE LOWER(rms_name) = LOWER('KARTHIK MALLI RAMESHBABU');
UPDATE employees SET siprahub_email = 'gundlururamakanth@siprahub.com', aws_email = 'gundluru.ramakanth@dcli.com' WHERE LOWER(rms_name) = LOWER('GUNDLURU RAMAKANTH');
UPDATE employees SET siprahub_email = 'madhankumar@siprahub.com' WHERE LOWER(rms_name) = LOWER('MadhanKumar Thangamani');
UPDATE employees SET siprahub_email = 'pratuldubey@siprahub.com' WHERE LOWER(rms_name) = LOWER('PRATUL DUBEY');
UPDATE employees SET siprahub_email = 'babasaheb@siprahub.com' WHERE LOWER(rms_name) = LOWER('Babasaheb Savkar Kokate');
UPDATE employees SET siprahub_email = 'ravikantpandurangi@siprahub.com' WHERE LOWER(rms_name) = LOWER('RAVIKANT PANDURANGI');
UPDATE employees SET siprahub_email = 'pujashree@siprahub.com' WHERE LOWER(rms_name) = LOWER('PUJASHREE Venkatesh');
UPDATE employees SET siprahub_email = 'bhargavkunamneni@siprahub.com', aws_email = 'bhargav.kunamneni@dcli.com' WHERE LOWER(rms_name) = LOWER('Bhargav Kunamneni');
UPDATE employees SET siprahub_email = 'parasgambhir@siprahub.com' WHERE LOWER(rms_name) = LOWER('PARAS GAMBHIR');
UPDATE employees SET siprahub_email = 'sandeepkumar@siprahub' WHERE LOWER(rms_name) = LOWER('SANDEEP KUMAR SAMUDRALA');
UPDATE employees SET siprahub_email = 'praveenhosamani@siprahub.com' WHERE LOWER(rms_name) = LOWER('PRAVEEN HOSAMANI');
UPDATE employees SET siprahub_email = 'praveenkondeti@siprahub.com', aws_email = 'praveen.kondeti@dcli.com' WHERE LOWER(rms_name) = LOWER('PRAVEEN KONDETI');
UPDATE employees SET siprahub_email = 'kirankumar@siprahub.com' WHERE LOWER(rms_name) = LOWER('Kiran Kumar N');
UPDATE employees SET siprahub_email = 'rishabhkalawatia@siprahub.com' WHERE LOWER(rms_name) = LOWER('RISHABH KALAWATIA');
UPDATE employees SET siprahub_email = 'saikrishna@siprahub.com' WHERE LOWER(rms_name) = LOWER('Sai Krishna');
UPDATE employees SET siprahub_email = 'danishnazir@siprahub.com', aws_email = 'danish.nazir@dcli.com' WHERE LOWER(rms_name) = LOWER('DANISH NAZIR');
UPDATE employees SET siprahub_email = 'chandrashakerreddy@siprahub.com' WHERE LOWER(rms_name) = LOWER('CHANDRASHAKERREDDY CHINTHAKUNTLA');
UPDATE employees SET siprahub_email = 'venkateswarareddy@siprahub.com' WHERE LOWER(rms_name) = LOWER('VENKATESWARA REDDY');
UPDATE employees SET siprahub_email = 'puneetnaik@siprahub.com' WHERE LOWER(rms_name) = LOWER('Puneet Naik');
UPDATE employees SET siprahub_email = 'satyalutukurthi@siprahub.com', aws_email = 'satya.lutukurthi@dcli.com' WHERE LOWER(rms_name) = LOWER('SATYA VARMA LUTUKURTHI');
UPDATE employees SET siprahub_email = 'binitabiswas@siprahub.com' WHERE LOWER(rms_name) = LOWER('BINITA ARUN BISWAS');
UPDATE employees SET siprahub_email = 'bharathgoud@siprahub.com' WHERE LOWER(rms_name) = LOWER('MUNUKUNTLA BHARATH GOUD');
UPDATE employees SET siprahub_email = 'monishagovardhanan@siprahub.com', aws_email = 'monisha.govardhanan@dcli.com' WHERE LOWER(rms_name) = LOWER('MONISHA VELLARI GOVARDHANAN');
UPDATE employees SET siprahub_email = 'davinadavis@siprahub.com' WHERE LOWER(rms_name) = LOWER('DAVINA DAVIS');
UPDATE employees SET siprahub_email = 'harishmunnangi@siprahub.com' WHERE LOWER(rms_name) = LOWER('HARISH KUMAR MUNNANGI');
UPDATE employees SET siprahub_email = 'girishkvns@siprahub.com' WHERE LOWER(rms_name) = LOWER('GIRISH KVNS');
UPDATE employees SET siprahub_email = 'smitkumarjadhao@siprahub.com' WHERE LOWER(rms_name) = LOWER('SMITKUMAR  JADHAO');
UPDATE employees SET siprahub_email = 'ramanathanr@siprahub.com', aws_email = 'ramanathan.ramanathan@dcli.com' WHERE LOWER(rms_name) = LOWER('RAMANATHAN RAMANATHAN');
UPDATE employees SET siprahub_email = 'navneetbajaj@siprahub.com', aws_email = 'navneet.bajaj@dcli.com' WHERE LOWER(rms_name) = LOWER('Navneet Bajaj');
UPDATE employees SET siprahub_email = 'anilvalluri@siprahub.com' WHERE LOWER(rms_name) = LOWER('ANIL VALLURI');
UPDATE employees SET siprahub_email = 'krishnabachu@siprahub.com' WHERE LOWER(rms_name) = LOWER('SAI KRISHNA BACHU');
UPDATE employees SET siprahub_email = 'dileepsahu@siprahub.com' WHERE LOWER(rms_name) = LOWER('DILEEP KUMAR SAHU');
UPDATE employees SET siprahub_email = 'srinivaskrishnan@siprahub.com', aws_email = 'srinivas.krishnan@dcli.com' WHERE LOWER(rms_name) = LOWER('SRINIVAS KRISHNAN');
UPDATE employees SET siprahub_email = 'gauravbansal@siprahub.com' WHERE LOWER(rms_name) = LOWER('GAURAV BANSAL');
UPDATE employees SET siprahub_email = 'asutoshswain@siprahub.com', aws_email = 'asutosh.swain@dcli.com' WHERE LOWER(rms_name) = LOWER('Asutosh Swain');
UPDATE employees SET siprahub_email = 'kishorekumar@siprahub.com' WHERE LOWER(rms_name) = LOWER('KISHORE KUMAR GUNTHA');
UPDATE employees SET siprahub_email = 'rahuls@siprahub.com' WHERE LOWER(rms_name) = LOWER('RAHUL SASI');
UPDATE employees SET siprahub_email = 'abhishekkishore@siprahub.com' WHERE LOWER(rms_name) = LOWER('ABHISHEK KISHORE');
UPDATE employees SET siprahub_email = 'sudhakarduppalapudi@siprahub.com' WHERE LOWER(rms_name) = LOWER('SUDHAKAR DUPPALAPUDI');
UPDATE employees SET siprahub_email = 'hycind.santhibhavan@siprahub.com', aws_email = 'hycind.santhibhavan@dcli.com' WHERE LOWER(rms_name) = LOWER('Hycind Santhibhavan');
UPDATE employees SET siprahub_email = 'sunithsamudrala@siprahub.com', aws_email = 'sunith.samudrala@dcli.com' WHERE LOWER(rms_name) = LOWER('Sunny K');
UPDATE employees SET siprahub_email = 'praneethpalepu@siprahub.com' WHERE LOWER(rms_name) = LOWER('PRANEETH KUMAR PALEPU');
UPDATE employees SET siprahub_email = 'kumarkarpuram@siprahub.com', aws_email = 'kumar.karpuram@dcli.com' WHERE LOWER(rms_name) = LOWER('KUMAR KARPURAM');
UPDATE employees SET siprahub_email = 'mahaveerkota@siprahub.com', aws_email = 'mahaveer.kota@dcli.com' WHERE LOWER(rms_name) = LOWER('MAHAVEER KOTA');
UPDATE employees SET siprahub_email = 'sajidkhaki@siprahub.com', aws_email = 'sajid.khaki@dcli.com' WHERE LOWER(rms_name) = LOWER('SAJID ASHRAF KHAKI');
UPDATE employees SET siprahub_email = 'gouthammavuri@siprahub.com' WHERE LOWER(rms_name) = LOWER('Goutham Mavuri');
UPDATE employees SET siprahub_email = 'adigarllababu@siprahub.com' WHERE LOWER(rms_name) = LOWER('ADIGARLLA JAGADEESH BABU');
UPDATE employees SET siprahub_email = 'sandeepsrinivas@siprahub.com' WHERE LOWER(rms_name) = LOWER('SANDEEP SRINIVAS');
UPDATE employees SET siprahub_email = 'saran.konduru@siprahub.com', aws_email = 'saran.konduru@dcli.com' WHERE LOWER(rms_name) = LOWER('SARAN RAJU KONDURU');
UPDATE employees SET siprahub_email = 'kasisrikakulapu@siprahub.com', aws_email = 'kasi.srikakulapu@dcli.com' WHERE LOWER(rms_name) = LOWER('KASI RAJESH SRIKAKULAPU');
UPDATE employees SET siprahub_email = 'ajazwagay@siprahub.com', aws_email = 'ajaz.wagay@dcli.com' WHERE LOWER(rms_name) = LOWER('AJAZ AHMAD WAGAY');
UPDATE employees SET siprahub_email = 'rajeshsai@siprahub.com', aws_email = 'rajesh.vurukonda@dcli.com' WHERE LOWER(rms_name) = LOWER('Rajesh Sai Krishna Vurukonda');
UPDATE employees SET siprahub_email = 'aurobindachand@siprahub.com' WHERE LOWER(rms_name) = LOWER('AUROBINDA CHAND');
UPDATE employees SET siprahub_email = 'mohdnayeem@siprahub.com' WHERE LOWER(rms_name) = LOWER('MOHD NAYEEM SHAH');
UPDATE employees SET siprahub_email = 'vikrambollam@siprahub.com' WHERE LOWER(rms_name) = LOWER('VIKRAM BOLLAM');
UPDATE employees SET siprahub_email = 'manikantaanisetti@siprahub.com' WHERE LOWER(rms_name) = LOWER('MANIKANTA ANISETTI');
UPDATE employees SET siprahub_email = 'saimopidevi@siprahub.com' WHERE LOWER(rms_name) = LOWER('SAI MOPIDEVI');
UPDATE employees SET siprahub_email = 'yoshinivinod@siprahub.com' WHERE LOWER(rms_name) = LOWER('Yoshini Vinod');
UPDATE employees SET siprahub_email = 'deepakmoodasarige@siprahub.com' WHERE LOWER(rms_name) = LOWER('DEEPAK MOODASARIGE');
UPDATE employees SET siprahub_email = 'karanamswetha@siprahub.com', aws_email = 'karanam.swetha@dcli.com' WHERE LOWER(rms_name) = LOWER('KARANAM SWETHA');
UPDATE employees SET siprahub_email = 'rakeshmanohar@siprahub.com', aws_email = 'rakesh.manohar@dcli.com' WHERE LOWER(rms_name) = LOWER('RAKESH MANOHAR');
UPDATE employees SET siprahub_email = 'tejachanta@siprahub.com' WHERE LOWER(rms_name) = LOWER('TEJ KUMAR ACHANTA');
UPDATE employees SET siprahub_email = 'bharatathota@siprahub.com', aws_email = 'bharat.athota@dcli.com' WHERE LOWER(rms_name) = LOWER('BHARAT ATHOTA');
UPDATE employees SET siprahub_email = 'vaibhavkadam@siprahub.com', aws_email = 'vaibhav.kadam@dcli.com' WHERE LOWER(rms_name) = LOWER('VAIBHAV KADAM');
UPDATE employees SET siprahub_email = 'tarunjain@siprahub.com', aws_email = 'tarun.jain@dcli.com' WHERE LOWER(rms_name) = LOWER('TARUN JAIN');
UPDATE employees SET siprahub_email = 'malladibabu@siprahub.com', aws_email = 'malladi.babu@dcli.com' WHERE LOWER(rms_name) = LOWER('MALLADI VEERA BABU');
UPDATE employees SET siprahub_email = 'roopiniarjunan@siprahub.com' WHERE LOWER(rms_name) = LOWER('ROOPINI ARJUNAN');
UPDATE employees SET siprahub_email = 'chaitanyaendluri@siprahub.com' WHERE LOWER(rms_name) = LOWER('CHAITANYA ENDLURI');
UPDATE employees SET siprahub_email = 'charantej@siprahub.com', aws_email = 'charan.tej@dcli.com' WHERE LOWER(rms_name) = LOWER('Charan Tej');
UPDATE employees SET siprahub_email = 'rajaj@siprahub.com' WHERE LOWER(rms_name) = LOWER('Raja Junaid');
UPDATE employees SET siprahub_email = 'jitendrasharma@siprahub.com' WHERE LOWER(rms_name) = LOWER('JITENDRA KUMAR SHARMA');
UPDATE employees SET siprahub_email = 'renukadakannagari@siprahub.com', aws_email = 'renuka.dakannagari@dcli.com' WHERE LOWER(rms_name) = LOWER('RENUKA DAKANNAGARI');
UPDATE employees SET siprahub_email = 'jaganrajgopal@siprahub.com' WHERE LOWER(rms_name) = LOWER('JAGAN RAJAGOPAL');
UPDATE employees SET siprahub_email = 'vinayhazare@siprahub.com' WHERE LOWER(rms_name) = LOWER('Vinay Hazare');
UPDATE employees SET siprahub_email = 'abhisheksharma@siprahub.com' WHERE LOWER(rms_name) = LOWER('Abhishek Sharma');
UPDATE employees SET siprahub_email = 'kranthkp@siprahub.com' WHERE LOWER(rms_name) = LOWER('KRANTHKUMAR POTHUGANTI');
UPDATE employees SET siprahub_email = 'manishsharma@siprahub.com' WHERE LOWER(rms_name) = LOWER('MANISH SHARMA');
UPDATE employees SET siprahub_email = 'juvviamaranth@siprahub.com' WHERE LOWER(rms_name) = LOWER('JUVVI SAI AMARANTH');
UPDATE employees SET siprahub_email = 'sonalsharma@siprahub.com' WHERE LOWER(rms_name) = LOWER('SONAL SHARMA');
UPDATE employees SET siprahub_email = 'bharathbhojappa@siprahub.com' WHERE LOWER(rms_name) = LOWER('BHARATH BHOJAPPA');
UPDATE employees SET siprahub_email = 'dheerajvarshney@siprahub.com' WHERE LOWER(rms_name) = LOWER('DHEERAJ VARSHNEY');
UPDATE employees SET siprahub_email = 'manishvashisht@siprahub.com' WHERE LOWER(rms_name) = LOWER('MANISH KUMAR VASHISHT');
UPDATE employees SET siprahub_email = 'raviramanujapu@siprahub.com', aws_email = 'ravi.ramanujapu@dcli.com' WHERE LOWER(rms_name) = LOWER('RAVI DUTT RAMANUJAPU');
UPDATE employees SET siprahub_email = 'krishnendraprakash@siprahub.com' WHERE LOWER(rms_name) = LOWER('KRISHNENDRA PRAKASH');
UPDATE employees SET siprahub_email = 'munibabuchittem@siprahub.com' WHERE LOWER(rms_name) = LOWER('MUNIBABU CHITTEM');
UPDATE employees SET siprahub_email = 'ranjeeta.yadav@siprahub.com' WHERE LOWER(rms_name) = LOWER('RANJEETA YADAV');
UPDATE employees SET siprahub_email = 'izhar.khan@siprahub.com' WHERE LOWER(rms_name) = LOWER('Izhar khan');
UPDATE employees SET siprahub_email = 'ashwarykaushik@siprahub.com' WHERE LOWER(rms_name) = LOWER('ASHWARY KAUSHIK');
UPDATE employees SET siprahub_email = 'harinath.sirigiri@siprahub.com', aws_email = 'harinath.sirigiri@dcli.com' WHERE LOWER(rms_name) = LOWER('HARINATH SIRIGIRI');
UPDATE employees SET siprahub_email = 'sudhakarreddy@siprahub.com' WHERE LOWER(rms_name) = LOWER('SUDHAKAR REDDY');
UPDATE employees SET siprahub_email = 'ravindrakumar@siprahub.com', aws_email = 'ravindra.kumar@dcli.com' WHERE LOWER(rms_name) = LOWER('RAVINDRA KUMAR');
UPDATE employees SET siprahub_email = 'ashwinitayade@siprahub.com', aws_email = 'ashwini.tayade@dcli.com' WHERE LOWER(rms_name) = LOWER('ASHWINI TAYADE');
UPDATE employees SET siprahub_email = 'mohammadshah@siprahub.com', aws_email = 'mohammad.shah@dcli.com' WHERE LOWER(rms_name) = LOWER('MOHAMMAD ILYAS SHAH');
UPDATE employees SET siprahub_email = 'ankitprasad@siprahub.com', aws_email = 'ankit.prasad@dcli.com' WHERE LOWER(rms_name) = LOWER('ANKIT PRASAD');
UPDATE employees SET siprahub_email = 'snehalpagare@siprahub.com' WHERE LOWER(rms_name) = LOWER('SNEHAL PAGARE');
UPDATE employees SET siprahub_email = 'sarbjitsingh@siprahub.com', aws_email = 'sarbjit.singh@dcli.com' WHERE LOWER(rms_name) = LOWER('SARBJIT SINGH');
UPDATE employees SET siprahub_email = 'nakulsulur@siprahub.com', aws_email = 'nakul.sulur@dcli.com' WHERE LOWER(rms_name) = LOWER('NAKUL SULUR');
UPDATE employees SET siprahub_email = 'rameshgopal@siprahub.com', aws_email = 'ramesh.gopal@dcli.com' WHERE LOWER(rms_name) = LOWER('RAMESH GOPAL');
UPDATE employees SET siprahub_email = 'mohinderreddy@siprahub.com', aws_email = 'mohinder.reddy@dcli.com' WHERE LOWER(rms_name) = LOWER('MOHINDER REDDY');
UPDATE employees SET siprahub_email = 'srirammurthy@siprahub.com', aws_email = 'srirama.vutukuri@dcli.com' WHERE LOWER(rms_name) = LOWER('Srirama Chandra Murthy Vutukuri');
UPDATE employees SET siprahub_email = 'prasadtavva@siprahub.com', aws_email = 'prasad.thavva@dcli.com' WHERE LOWER(rms_name) = LOWER('PRASAD THAVVA');
UPDATE employees SET siprahub_email = 'ananth.malyala@siprahub.com', aws_email = 'ananth.malyala@dcli.com' WHERE LOWER(rms_name) = LOWER('Ananth Malyala');
UPDATE employees SET siprahub_email = 'kaushikmv@siprahub.com' WHERE LOWER(rms_name) = LOWER('Kaushik Volety');
UPDATE employees SET siprahub_email = 'rahulkemani@siprahub.com' WHERE LOWER(rms_name) = LOWER('RAHUL KEMANI');
UPDATE employees SET siprahub_email = 'yuvansureshkumar@siprahub.com', aws_email = 'yuvan.sureshkumar@dcli.com' WHERE LOWER(rms_name) = LOWER('Yuvan S');
UPDATE employees SET siprahub_email = 'mohitsharwan@siprahub.com', aws_email = 'mohit.sharwan@dcli.com' WHERE LOWER(rms_name) = LOWER('MOHIT SHARWAN');
UPDATE employees SET siprahub_email = 'jyothib@siprahub.com' WHERE LOWER(rms_name) = LOWER('JYOTHI BHARTHEPUDI');
UPDATE employees SET siprahub_email = 'raviteja@siprahub.com' WHERE LOWER(rms_name) = LOWER('RAVI TEJA SANNIDHANAM');
UPDATE employees SET siprahub_email = 'prachisoumya@siprahub.com' WHERE LOWER(rms_name) = LOWER('PRACHI SOUMYA');
UPDATE employees SET siprahub_email = 'srinivasvykuntapu@siprahub.com', aws_email = 'srinivas.vykuntapu@dcli.com' WHERE LOWER(rms_name) = LOWER('SRINIVAS VYKUNTAPU');
UPDATE employees SET siprahub_email = 'nagarjunareddy@siprahub.com', aws_email = 'nagarjuna.reddy@dcli.com' WHERE LOWER(rms_name) = LOWER('NAGARJUNA REDDY');
UPDATE employees SET siprahub_email = 'zahidahangar@siprahub.com', aws_email = 'zahid.ahangar@dcli.com' WHERE LOWER(rms_name) = LOWER('Zahid Majeed Ahangar');
UPDATE employees SET siprahub_email = 'hareeshpitchikala@siprahub.com' WHERE LOWER(rms_name) = LOWER('HAREESH PITCHIKALA');
UPDATE employees SET siprahub_email = 'vivek.vashistha@siprahub.com', aws_email = 'vivek.vashistha@dcli.com' WHERE LOWER(rms_name) = LOWER('VIVEK VASHISTHA');
UPDATE employees SET siprahub_email = 'lakshmirajesh@siprahub.com', aws_email = 'lakshmi.rajesh@dcli.com' WHERE LOWER(rms_name) = LOWER('Rajesh Lakshmi');
UPDATE employees SET siprahub_email = 'abhilash.m@siprahub.com', aws_email = 'abhilash.malka@dcli.com' WHERE LOWER(rms_name) = LOWER('ABHILASH MALKA');
UPDATE employees SET siprahub_email = 'ramakrishna.dadi@siprahub.com', aws_email = 'ramakrishna.dadi@dcli.com' WHERE LOWER(rms_name) = LOWER('RAMAKRISHNA DADI');
UPDATE employees SET siprahub_email = 'anusha.pochimcherla@siprahub.com', aws_email = 'anusha.pochimcherla@dcli.com' WHERE LOWER(rms_name) = LOWER('VANI ANUSHA POCHIMCHERLA');
UPDATE employees SET siprahub_email = 'praneeth.joggala@siprahub.com' WHERE LOWER(rms_name) = LOWER('PRANEETH JOGGALA');
UPDATE employees SET siprahub_email = 'mahesh.paidi@siprahub.com' WHERE LOWER(rms_name) = LOWER('MAHESH PAIDI');
UPDATE employees SET siprahub_email = 'amol.wankhede@siprahub.com', aws_email = 'amol.wankhede@dcli.com' WHERE LOWER(rms_name) = LOWER('Amol Wankhede');
UPDATE employees SET siprahub_email = 'vinayaka.dharmasthala@siprahub.com' WHERE LOWER(rms_name) = LOWER('Vinayaka Dharmasthala');
UPDATE employees SET siprahub_email = 'satish.pogakula@siprahub.com', aws_email = 'satish.pogakula@dcli.com' WHERE LOWER(rms_name) = LOWER('Satish Pogakula');
UPDATE employees SET siprahub_email = 'ajay.ramaprasanna@siprahub.com' WHERE LOWER(rms_name) = LOWER('AJAY RAMAPRASANNA');
UPDATE employees SET siprahub_email = 'raj.tripathi@siprahub.com' WHERE LOWER(rms_name) = LOWER('Raj Tripathi');
UPDATE employees SET siprahub_email = 'siva.reddy@siprahub.com', aws_email = 'siva.reddy@dcli.com' WHERE LOWER(rms_name) = LOWER('SIVA REDDY');
UPDATE employees SET siprahub_email = 'venkata.madalam@siprahub.com', aws_email = 'venkata.madalam@dcli.com' WHERE LOWER(rms_name) = LOWER('VENKATA MADALAM');
UPDATE employees SET siprahub_email = 'prakash.kj@siprahub.com', aws_email = 'kj.prakash@dcli.com' WHERE LOWER(rms_name) = LOWER('KJ PRAKASH');
UPDATE employees SET siprahub_email = 'juned.soneji@siprahub.com', aws_email = 'juned.soneji@dcli.com' WHERE LOWER(rms_name) = LOWER('JUNED SONEJI');
UPDATE employees SET siprahub_email = 'ramanjine.vankayalapati@siprahub.com', aws_email = 'ramanjineyalu.vankayalapati@dcli.com' WHERE LOWER(rms_name) = LOWER('RAMANJINEYALU VANKAYALAPATI');
UPDATE employees SET siprahub_email = 'pradeep.kushwaha@siprahub.com', aws_email = 'pradeep.kushwaha@dcli.com' WHERE LOWER(rms_name) = LOWER('Pradeep Kushwaha');